"""empty message

Revision ID: 6cbdf49897d3
Revises: a5cffa318ac2
Create Date: 2025-07-11 19:03:28.055490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbdf49897d3'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('clima', sa.String(length=120), nullable=False),
    sa.Column('terreno', sa.String(length=120), nullable=False),
    sa.Column('poblacion', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.Enum('male', 'female', 'n/a', 'unknown', name='genero_enum'), nullable=False),
    sa.Column('raza', sa.String(length=80), nullable=False),
    sa.Column('planeta_origen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planeta_origen_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    op.drop_table('planets')
    # ### end Alembic commands ###
