"""empty message

Revision ID: 7684167f9536
Revises: 9504b7ae1d05
Create Date: 2025-07-16 13:58:29.686140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7684167f9536'
down_revision = '9504b7ae1d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorite_character_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'characters', ['favorite_character_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['favorite_planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_character_id')
        batch_op.drop_column('favorite_planet_id')

    # ### end Alembic commands ###
