"""empty message

Revision ID: 9504b7ae1d05
Revises: 6cbdf49897d3
Create Date: 2025-07-14 18:11:23.054345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9504b7ae1d05'
down_revision = '6cbdf49897d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_planeta_origen_id_fkey', type_='foreignkey')
        batch_op.drop_column('planeta_origen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_origen_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('characters_planeta_origen_id_fkey', 'planets', ['planeta_origen_id'], ['id'])

    # ### end Alembic commands ###
