"""empty message

Revision ID: d1c3306fe8fc
Revises: 7684167f9536
Create Date: 2025-07-16 15:22:47.948820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c3306fe8fc'
down_revision = '7684167f9536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planeta_origen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planets', ['planeta_origen_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planeta_origen_id')

    # ### end Alembic commands ###
